/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhySanyyaRouteImport } from './routes/why-sanyya'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIndexRouteImport } from './routes/product.index'
import { Route as SolutionsSplatRouteImport } from './routes/solutions.$'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'

const WhySanyyaRoute = WhySanyyaRouteImport.update({
  id: '/why-sanyya',
  path: '/why-sanyya',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIndexRoute = ProductIndexRouteImport.update({
  id: '/product/',
  path: '/product/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsSplatRoute = SolutionsSplatRouteImport.update({
  id: '/solutions/$',
  path: '/solutions/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/integrations': typeof IntegrationsRoute
  '/pricing': typeof PricingRoute
  '/why-sanyya': typeof WhySanyyaRoute
  '/product/$slug': typeof ProductSlugRoute
  '/solutions/$': typeof SolutionsSplatRoute
  '/product/': typeof ProductIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/integrations': typeof IntegrationsRoute
  '/pricing': typeof PricingRoute
  '/why-sanyya': typeof WhySanyyaRoute
  '/product/$slug': typeof ProductSlugRoute
  '/solutions/$': typeof SolutionsSplatRoute
  '/product': typeof ProductIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/integrations': typeof IntegrationsRoute
  '/pricing': typeof PricingRoute
  '/why-sanyya': typeof WhySanyyaRoute
  '/product/$slug': typeof ProductSlugRoute
  '/solutions/$': typeof SolutionsSplatRoute
  '/product/': typeof ProductIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/integrations'
    | '/pricing'
    | '/why-sanyya'
    | '/product/$slug'
    | '/solutions/$'
    | '/product/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/integrations'
    | '/pricing'
    | '/why-sanyya'
    | '/product/$slug'
    | '/solutions/$'
    | '/product'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/integrations'
    | '/pricing'
    | '/why-sanyya'
    | '/product/$slug'
    | '/solutions/$'
    | '/product/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  IntegrationsRoute: typeof IntegrationsRoute
  PricingRoute: typeof PricingRoute
  WhySanyyaRoute: typeof WhySanyyaRoute
  ProductSlugRoute: typeof ProductSlugRoute
  SolutionsSplatRoute: typeof SolutionsSplatRoute
  ProductIndexRoute: typeof ProductIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-sanyya': {
      id: '/why-sanyya'
      path: '/why-sanyya'
      fullPath: '/why-sanyya'
      preLoaderRoute: typeof WhySanyyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/': {
      id: '/product/'
      path: '/product'
      fullPath: '/product/'
      preLoaderRoute: typeof ProductIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/$': {
      id: '/solutions/$'
      path: '/solutions/$'
      fullPath: '/solutions/$'
      preLoaderRoute: typeof SolutionsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  IntegrationsRoute: IntegrationsRoute,
  PricingRoute: PricingRoute,
  WhySanyyaRoute: WhySanyyaRoute,
  ProductSlugRoute: ProductSlugRoute,
  SolutionsSplatRoute: SolutionsSplatRoute,
  ProductIndexRoute: ProductIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
