/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhySanyyaRouteImport } from './routes/why-sanyya'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolutionsProcurementRouteImport } from './routes/solutions.procurement'
import { Route as SolutionsOperationsRouteImport } from './routes/solutions.operations'
import { Route as SolutionsHardwareRouteImport } from './routes/solutions.hardware'
import { Route as SolutionsFinanceRouteImport } from './routes/solutions.finance'
import { Route as SolutionsBiotechRouteImport } from './routes/solutions.biotech'
import { Route as ProductVendorsRouteImport } from './routes/product.vendors'
import { Route as ProductSanyyaDriveRouteImport } from './routes/product.sanyya-drive'
import { Route as ProductRequisitionsRouteImport } from './routes/product.requisitions'
import { Route as ProductReceivingRouteImport } from './routes/product.receiving'
import { Route as ProductQuotesRouteImport } from './routes/product.quotes'
import { Route as ProductPurchaseOrdersRouteImport } from './routes/product.purchase-orders'
import { Route as ProductMatchEngineRouteImport } from './routes/product.match-engine'
import { Route as ProductInvoicesRouteImport } from './routes/product.invoices'
import { Route as ProductInventoryRouteImport } from './routes/product.inventory'
import { Route as ProductDashboardsRouteImport } from './routes/product.dashboards'
import { Route as ProductApprovalsRouteImport } from './routes/product.approvals'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'

const WhySanyyaRoute = WhySanyyaRouteImport.update({
  id: '/why-sanyya',
  path: '/why-sanyya',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsProcurementRoute = SolutionsProcurementRouteImport.update({
  id: '/solutions/procurement',
  path: '/solutions/procurement',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsOperationsRoute = SolutionsOperationsRouteImport.update({
  id: '/solutions/operations',
  path: '/solutions/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsHardwareRoute = SolutionsHardwareRouteImport.update({
  id: '/solutions/hardware',
  path: '/solutions/hardware',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsFinanceRoute = SolutionsFinanceRouteImport.update({
  id: '/solutions/finance',
  path: '/solutions/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsBiotechRoute = SolutionsBiotechRouteImport.update({
  id: '/solutions/biotech',
  path: '/solutions/biotech',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductVendorsRoute = ProductVendorsRouteImport.update({
  id: '/product/vendors',
  path: '/product/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSanyyaDriveRoute = ProductSanyyaDriveRouteImport.update({
  id: '/product/sanyya-drive',
  path: '/product/sanyya-drive',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRequisitionsRoute = ProductRequisitionsRouteImport.update({
  id: '/product/requisitions',
  path: '/product/requisitions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductReceivingRoute = ProductReceivingRouteImport.update({
  id: '/product/receiving',
  path: '/product/receiving',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductQuotesRoute = ProductQuotesRouteImport.update({
  id: '/product/quotes',
  path: '/product/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductPurchaseOrdersRoute = ProductPurchaseOrdersRouteImport.update({
  id: '/product/purchase-orders',
  path: '/product/purchase-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductMatchEngineRoute = ProductMatchEngineRouteImport.update({
  id: '/product/match-engine',
  path: '/product/match-engine',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductInvoicesRoute = ProductInvoicesRouteImport.update({
  id: '/product/invoices',
  path: '/product/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductInventoryRoute = ProductInventoryRouteImport.update({
  id: '/product/inventory',
  path: '/product/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductDashboardsRoute = ProductDashboardsRouteImport.update({
  id: '/product/dashboards',
  path: '/product/dashboards',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductApprovalsRoute = ProductApprovalsRouteImport.update({
  id: '/product/approvals',
  path: '/product/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/integrations': typeof IntegrationsRoute
  '/pricing': typeof PricingRoute
  '/why-sanyya': typeof WhySanyyaRoute
  '/product/$slug': typeof ProductSlugRoute
  '/product/approvals': typeof ProductApprovalsRoute
  '/product/dashboards': typeof ProductDashboardsRoute
  '/product/inventory': typeof ProductInventoryRoute
  '/product/invoices': typeof ProductInvoicesRoute
  '/product/match-engine': typeof ProductMatchEngineRoute
  '/product/purchase-orders': typeof ProductPurchaseOrdersRoute
  '/product/quotes': typeof ProductQuotesRoute
  '/product/receiving': typeof ProductReceivingRoute
  '/product/requisitions': typeof ProductRequisitionsRoute
  '/product/sanyya-drive': typeof ProductSanyyaDriveRoute
  '/product/vendors': typeof ProductVendorsRoute
  '/solutions/biotech': typeof SolutionsBiotechRoute
  '/solutions/finance': typeof SolutionsFinanceRoute
  '/solutions/hardware': typeof SolutionsHardwareRoute
  '/solutions/operations': typeof SolutionsOperationsRoute
  '/solutions/procurement': typeof SolutionsProcurementRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/integrations': typeof IntegrationsRoute
  '/pricing': typeof PricingRoute
  '/why-sanyya': typeof WhySanyyaRoute
  '/product/$slug': typeof ProductSlugRoute
  '/product/approvals': typeof ProductApprovalsRoute
  '/product/dashboards': typeof ProductDashboardsRoute
  '/product/inventory': typeof ProductInventoryRoute
  '/product/invoices': typeof ProductInvoicesRoute
  '/product/match-engine': typeof ProductMatchEngineRoute
  '/product/purchase-orders': typeof ProductPurchaseOrdersRoute
  '/product/quotes': typeof ProductQuotesRoute
  '/product/receiving': typeof ProductReceivingRoute
  '/product/requisitions': typeof ProductRequisitionsRoute
  '/product/sanyya-drive': typeof ProductSanyyaDriveRoute
  '/product/vendors': typeof ProductVendorsRoute
  '/solutions/biotech': typeof SolutionsBiotechRoute
  '/solutions/finance': typeof SolutionsFinanceRoute
  '/solutions/hardware': typeof SolutionsHardwareRoute
  '/solutions/operations': typeof SolutionsOperationsRoute
  '/solutions/procurement': typeof SolutionsProcurementRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/integrations': typeof IntegrationsRoute
  '/pricing': typeof PricingRoute
  '/why-sanyya': typeof WhySanyyaRoute
  '/product/$slug': typeof ProductSlugRoute
  '/product/approvals': typeof ProductApprovalsRoute
  '/product/dashboards': typeof ProductDashboardsRoute
  '/product/inventory': typeof ProductInventoryRoute
  '/product/invoices': typeof ProductInvoicesRoute
  '/product/match-engine': typeof ProductMatchEngineRoute
  '/product/purchase-orders': typeof ProductPurchaseOrdersRoute
  '/product/quotes': typeof ProductQuotesRoute
  '/product/receiving': typeof ProductReceivingRoute
  '/product/requisitions': typeof ProductRequisitionsRoute
  '/product/sanyya-drive': typeof ProductSanyyaDriveRoute
  '/product/vendors': typeof ProductVendorsRoute
  '/solutions/biotech': typeof SolutionsBiotechRoute
  '/solutions/finance': typeof SolutionsFinanceRoute
  '/solutions/hardware': typeof SolutionsHardwareRoute
  '/solutions/operations': typeof SolutionsOperationsRoute
  '/solutions/procurement': typeof SolutionsProcurementRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/integrations'
    | '/pricing'
    | '/why-sanyya'
    | '/product/$slug'
    | '/product/approvals'
    | '/product/dashboards'
    | '/product/inventory'
    | '/product/invoices'
    | '/product/match-engine'
    | '/product/purchase-orders'
    | '/product/quotes'
    | '/product/receiving'
    | '/product/requisitions'
    | '/product/sanyya-drive'
    | '/product/vendors'
    | '/solutions/biotech'
    | '/solutions/finance'
    | '/solutions/hardware'
    | '/solutions/operations'
    | '/solutions/procurement'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/integrations'
    | '/pricing'
    | '/why-sanyya'
    | '/product/$slug'
    | '/product/approvals'
    | '/product/dashboards'
    | '/product/inventory'
    | '/product/invoices'
    | '/product/match-engine'
    | '/product/purchase-orders'
    | '/product/quotes'
    | '/product/receiving'
    | '/product/requisitions'
    | '/product/sanyya-drive'
    | '/product/vendors'
    | '/solutions/biotech'
    | '/solutions/finance'
    | '/solutions/hardware'
    | '/solutions/operations'
    | '/solutions/procurement'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/integrations'
    | '/pricing'
    | '/why-sanyya'
    | '/product/$slug'
    | '/product/approvals'
    | '/product/dashboards'
    | '/product/inventory'
    | '/product/invoices'
    | '/product/match-engine'
    | '/product/purchase-orders'
    | '/product/quotes'
    | '/product/receiving'
    | '/product/requisitions'
    | '/product/sanyya-drive'
    | '/product/vendors'
    | '/solutions/biotech'
    | '/solutions/finance'
    | '/solutions/hardware'
    | '/solutions/operations'
    | '/solutions/procurement'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  IntegrationsRoute: typeof IntegrationsRoute
  PricingRoute: typeof PricingRoute
  WhySanyyaRoute: typeof WhySanyyaRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ProductApprovalsRoute: typeof ProductApprovalsRoute
  ProductDashboardsRoute: typeof ProductDashboardsRoute
  ProductInventoryRoute: typeof ProductInventoryRoute
  ProductInvoicesRoute: typeof ProductInvoicesRoute
  ProductMatchEngineRoute: typeof ProductMatchEngineRoute
  ProductPurchaseOrdersRoute: typeof ProductPurchaseOrdersRoute
  ProductQuotesRoute: typeof ProductQuotesRoute
  ProductReceivingRoute: typeof ProductReceivingRoute
  ProductRequisitionsRoute: typeof ProductRequisitionsRoute
  ProductSanyyaDriveRoute: typeof ProductSanyyaDriveRoute
  ProductVendorsRoute: typeof ProductVendorsRoute
  SolutionsBiotechRoute: typeof SolutionsBiotechRoute
  SolutionsFinanceRoute: typeof SolutionsFinanceRoute
  SolutionsHardwareRoute: typeof SolutionsHardwareRoute
  SolutionsOperationsRoute: typeof SolutionsOperationsRoute
  SolutionsProcurementRoute: typeof SolutionsProcurementRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-sanyya': {
      id: '/why-sanyya'
      path: '/why-sanyya'
      fullPath: '/why-sanyya'
      preLoaderRoute: typeof WhySanyyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/procurement': {
      id: '/solutions/procurement'
      path: '/solutions/procurement'
      fullPath: '/solutions/procurement'
      preLoaderRoute: typeof SolutionsProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/operations': {
      id: '/solutions/operations'
      path: '/solutions/operations'
      fullPath: '/solutions/operations'
      preLoaderRoute: typeof SolutionsOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/hardware': {
      id: '/solutions/hardware'
      path: '/solutions/hardware'
      fullPath: '/solutions/hardware'
      preLoaderRoute: typeof SolutionsHardwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/finance': {
      id: '/solutions/finance'
      path: '/solutions/finance'
      fullPath: '/solutions/finance'
      preLoaderRoute: typeof SolutionsFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/biotech': {
      id: '/solutions/biotech'
      path: '/solutions/biotech'
      fullPath: '/solutions/biotech'
      preLoaderRoute: typeof SolutionsBiotechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/vendors': {
      id: '/product/vendors'
      path: '/product/vendors'
      fullPath: '/product/vendors'
      preLoaderRoute: typeof ProductVendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/sanyya-drive': {
      id: '/product/sanyya-drive'
      path: '/product/sanyya-drive'
      fullPath: '/product/sanyya-drive'
      preLoaderRoute: typeof ProductSanyyaDriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/requisitions': {
      id: '/product/requisitions'
      path: '/product/requisitions'
      fullPath: '/product/requisitions'
      preLoaderRoute: typeof ProductRequisitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/receiving': {
      id: '/product/receiving'
      path: '/product/receiving'
      fullPath: '/product/receiving'
      preLoaderRoute: typeof ProductReceivingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/quotes': {
      id: '/product/quotes'
      path: '/product/quotes'
      fullPath: '/product/quotes'
      preLoaderRoute: typeof ProductQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/purchase-orders': {
      id: '/product/purchase-orders'
      path: '/product/purchase-orders'
      fullPath: '/product/purchase-orders'
      preLoaderRoute: typeof ProductPurchaseOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/match-engine': {
      id: '/product/match-engine'
      path: '/product/match-engine'
      fullPath: '/product/match-engine'
      preLoaderRoute: typeof ProductMatchEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/invoices': {
      id: '/product/invoices'
      path: '/product/invoices'
      fullPath: '/product/invoices'
      preLoaderRoute: typeof ProductInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/inventory': {
      id: '/product/inventory'
      path: '/product/inventory'
      fullPath: '/product/inventory'
      preLoaderRoute: typeof ProductInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/dashboards': {
      id: '/product/dashboards'
      path: '/product/dashboards'
      fullPath: '/product/dashboards'
      preLoaderRoute: typeof ProductDashboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/approvals': {
      id: '/product/approvals'
      path: '/product/approvals'
      fullPath: '/product/approvals'
      preLoaderRoute: typeof ProductApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  IntegrationsRoute: IntegrationsRoute,
  PricingRoute: PricingRoute,
  WhySanyyaRoute: WhySanyyaRoute,
  ProductSlugRoute: ProductSlugRoute,
  ProductApprovalsRoute: ProductApprovalsRoute,
  ProductDashboardsRoute: ProductDashboardsRoute,
  ProductInventoryRoute: ProductInventoryRoute,
  ProductInvoicesRoute: ProductInvoicesRoute,
  ProductMatchEngineRoute: ProductMatchEngineRoute,
  ProductPurchaseOrdersRoute: ProductPurchaseOrdersRoute,
  ProductQuotesRoute: ProductQuotesRoute,
  ProductReceivingRoute: ProductReceivingRoute,
  ProductRequisitionsRoute: ProductRequisitionsRoute,
  ProductSanyyaDriveRoute: ProductSanyyaDriveRoute,
  ProductVendorsRoute: ProductVendorsRoute,
  SolutionsBiotechRoute: SolutionsBiotechRoute,
  SolutionsFinanceRoute: SolutionsFinanceRoute,
  SolutionsHardwareRoute: SolutionsHardwareRoute,
  SolutionsOperationsRoute: SolutionsOperationsRoute,
  SolutionsProcurementRoute: SolutionsProcurementRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
